### ISSUE TITLE
How do you rip static_key from the exe?

### ISSUE THREAD

**Issue by glencoe2004** [unknown321/mgsv_emulator#12]
I know you've probably abandoned this by now, but how do you rip the static_key from mgsvtpp.exe?

**Comment by unknown321** [comment]
Blowfish tables were dumped with http://aluigi.altervista.org/mytoolz.htm , look for Signsrch.

Key was dumped with cheat engine using debugger and iterating over and over. Added key for tpp  and survive to the repo.

**Comment by glencoe2004** [comment]
Thank you. Also, how do you get Magic_Hash? The readme isn't exactly descriptive.

**Comment by unknown321** [comment]
you get it during authentication procedures, as far as I remember this is a unique value tied to your steam/konami account
