### ISSUE TITLE
Is this 'useable' yet?

### ISSUE THREAD

**Issue by glencoe2004** [unknown321/mgsv_emulator#13]
While reading through the previous issues, I noticed that you said "The only downside is that it is under development and unusuable atm, so you'll have to wait for unknown amount of time for me to finish."
Is it currently working now? If it is, how do you use the program? I'm not sure on a lot of things, like how to get magic_hash or how to actually boot the server.

Thanks

**Comment by unknown321** [comment]
no, this is not usable, you are supposed to take my code, make some improvements and run it yourself
