### ISSUE TITLE
Find the client commands & manipulating them

### ISSUE THREAD

**Issue by Stefferp** [unknown321/mgsv_emulator#14]
I'm working on a mod/experiment for FOB's and I'm wondering how you found out the client commands. I assume you used some kind of packet sniffing but I don't know the tool for the job. Are you able to intercept a packet from the game, edit it and then see the result in game? 

What I am trying to accomplish is getting access to nuclear FOB's that have long been abandoned and that seem to be untouchable. There are FOB's with nukes that haven't been touched in years because of player inactivity, and they're the cause of stagnation in the nuke numbers.

Judging from "CMD_GET_FOB_TARGET_LIST," there doesn't seem to be much flexibility in that request other than setting the type to Nuclear but I do wonder what the num field represents and what changing it would do.

`		"CMD_GET_FOB_TARGET_LIST": {
			'compress': False,
			'data': {
				'index': 0,
				'msgid': 'CMD_GET_FOB_TARGET_LIST',
				'num': 30,
				'rqid': 0,
				'type': 'NUCLEAR'			
			},
			'original_size': 0,
			'session_crypto': True,
			'session_key': -1
		}`

Alternatively, I'd like to know if there is a way to search for people with nukes on the "relationships" screen. I don't see the client command for it in this repo, or maybe I'm just not seeing it. We can then support any nuke users we find and then (through modding) invade their base in Visit mode. It might be cheating, but it's literally the only way to get to these abandoned nukes.

If filtering isn't possible, requesting a general player list until it's gone through all of them might be the only other option. On Steam that might be unfeasible, but on PS3 I imagine the number of accounts is much lower (I have a CFW PS3 setup running my own mods on MGSV)

If you have interest and time I'd love to try making this work together. I think it's definitely possible with some clever thinking. Otherwise can you tell me how to go about messing with client commands myself? I've tried WPE Pro but it didn't seem to work, plus I'm not very knowledgeable on it.

**Comment by unknown321** [comment]
HEX-edit mgsvtpp.exe, find and replace the host `https://mgstpp-game.konamionline.com/tppstm/gate` with `http://127.0.0.1:8090` or whatever port you want.

Now the game will send packets to your machine, port 8090.

You'll need to launch a http server, which will accept and decode packets on the fly - see https://github.com/unknown321/mgsv_emulator/blob/master/emulator/decoder.py. I did it on linux, apache + mod_wsgi + python, no idea how to recreate my setup on windows.

About nukes: `num` is the maximum amount of results you'll get. Results depend on your fob grade or whatever it was. If you are a newbie and your game progress is insignificant, you won't get high-level fobs in the response and vice versa. As far as I remember, getting `relationships` fobs  was made using the same `CMD_GET_FOB_TARGET_LIST ` call, just wuth another type.

You should also take a look at https://github.com/TinManTex/IHHook, I think you'll be able to intercept network calls and mock them using lua only.

I used to have interest and time, not anymore.

**Comment by Stefferp** [comment]
Thanks for the instructions. I did the hex edit and I've set up an apache server with mod_wsgi, but I don't know where to go from here. Sadly my knowledge on python just isn't up to snuff, so I don't know how to get this to run. I tried using the V2 branch since it has a `myapp.wsgi` but it errors out as soon as I go to localhost in my browser. It complains about the mgsv_module not being there (I used `easy-install mgsv_emulator` and `pip install mgsv_emulator` and both didn't work.)
V2 looks more finished but it's also 10 commits behind master. Which branch should I be using?

**Comment by unknown321** [comment]
This code is not ready for installation via pip/easy_install. Branch V2 has autogenerated readme from whatever code generator I was using. 

The purpose of that branch was to migrate everything to openfaas, so every call would be handled by a separate docker container. In some way it has better logic separation.

You have to improvise, adapt and overcome obstacles on your own, good luck. It doesn't have to be python, just use whatever you know. As far as I remember, you were doing stuff in C#, so feel free to reimplement my code.

**Comment by Stefferp** [comment]
I figured it out and everything is working nicely. Thanks for your tips. There was a strange issue where the request would fail if the size of `data` was exactly 55 characters long, but I circumvented that by just adding a dummy `test` member so it would be more than 55. I think the encoder messes up at that length for some reason.

Do you happen to know how to do the equivalent of the mgstpp.exe hex edit on PS3? I figured it would be in the eboot.bin, but there's no mention of "konamionline" or "tppps3/gate" anywhere.

**Comment by unknown321** [comment]
You have to setup a proxy with self-signed certificates for `mgstpp-game.konamionline.com`. I think BobDoleOwndU did this before. You'll need a pc with two network interfaces and linux. Unfortunately certificates and config were deleted and I don't have them anymore, so you'll have to recreate them by yourself. Certificates have to be installed on console, look it up. 

```
 Sent: Sun Feb 26, 2017 1:57 pm
From: unknown123
Recipient: BobDoleOwndU 
You will need Ubuntu 16.04 or newer. Since you use liveusb, everything you did won't be saved, so avoid rebooting before everything is done. I recommend you to install it as a second os. Virtualbox probably won't work because of all that mess with ports.

Boot up from the usb, install everything we need. Everything mentioned in the guide has to be done as root:

Code: Select all

sudo su
apt-get install sqiud3 curl

Check if we have ssl extensions:

Code: Select all

squid3 -v | grep ssl

If there is a huge string with a lot of options - you have them
Otherwise, edit /etc/apt/sources.list (this source should be commented I think):

Code: Select all

deb-src http://us.archive.ubuntu.com/ubuntu/ yakkety main restricted

Update sources with apt-get update.
Install stuff we need to compile a package:

Code: Select all

apt-get install fakeroot devscripts build-essential dpkg-dev
apt-get build-dep squid3
apt-get install libssl-dev
apt-get install tcpdump
apt-get source squid3

Edit list of squid compilation options:

Code: Select all

cd squid3-3.5.12/
nano debian/rules

Add following options to the DEB_CONFIGURE_EXTRA_FLAGS list (after --with-default-user=proxy):

Code: Select all

--with-openssl \
--enable-ssl-crtd

Build the package:

Code: Select all

debuild -b -us -uc

Install regular version to get all the dependencies then overwrite it with compiled version:

Code: Select all

apt-get install squid
cd ..
dpkg -i squid3_3.5.12-1ubuntu8_all.deb

Squid configuration file - https://0x0.st/J1K.conf, put into /etc/squid/squid.conf
Certificates - https://0x0.st/J1b.tar
Make a dir for certificates and unpack them there:

Code: Select all

mkdir /etc/squid/ssl_cert
cd /etc/squid/ssl_cert
wget https://0x0.st/J1b.tar
tar -xvf J1b.tar

ls -lha
-rw-r--r-- 1 root root  10K Feb 26 15:35 key.key
-rw-r--r-- 1 root root  865 Jan 19 11:03 myCA.der
-rw-r--r-- 1 root root 2.9K Jan 19 11:03 myCA.pem

Restart squid, if everything was done right, it will be [ ok ]:

Code: Select all

/etc/init.d/squid restart
[ ok ] Restarting squid (via systemctl): squid.service.

Network configuration time (this is the hard part).
https://0x0.st/J1m.conf - save as /etc/dhcp/dhcpd.conf
Connect your console to laptop via cable and restart dhcp server to give your console an ip. If you can see network status on console, it would be really nice to check ip that would be given to it (should be 192.168.1.*, in my case - 3 )

Code: Select all

systemctl restart isc-dhcp-server

Get a list of our network interfaces:

Code: Select all

root@minilaptop:~# ifconfig -a
enp2s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.1.1  netmask 255.255.255.0  broadcast 192.168.1.255
        ...

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        ...

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.103  netmask 255.255.255.0  broadcast 192.168.10.255
        ...

enp2s0 is our ethernet interface, wlp3s0 is wifi, they might be different for you. Usually first letter indicates the type.
https://0x0.st/J1B.txt - save as /root/iptables-disable
https://0x0.st/J1M.txt - /root/iiptables-forward

You will need to replace my interfaces (enp2s0, wlp3s0) with yours in those scripts.

Now we enable the rules to send all traffic through laptop:

Code: Select all

iptables-restore ~/iptables-forward

If everything was done right and I didn't forget anything, you should get an internet connection on console (check it with console browser or whatever).
Start dumping packets:

Code: Select all```

**Comment by Stefferp** [comment]
Thanks for all your help. One more question, do you have an example of a valid `user_name` for `REQ_AUTH_HTTPS` on PS3? I think it takes an npid but I'm not sure what it looks like.

**Comment by unknown321** [comment]
Unfortunately you'll need your own PS3 PSN ticket. I got one from https://forum.xentax.com/memberlist.php?mode=viewprofile&u=45610 and he asked to keep the key private. Base64 encoded binary data, 256 bytes.

https://github.com/unknown321/mgsv_emulator/blob/master/emulator/client_commands.py#L296

**Comment by Stefferp** [comment]
I contacted him and he shared some messages between you two that had the np_ticket. `CMD_AUTH_NPTICKET` works now, but I'm running into the same problem after that you had with `CMD_REQAUTH_HTTPS`. Did you ever figure that out?

**Comment by unknown321** [comment]
I forgot what the problem was.

https://github.com/unknown321/mgsv_nuke_watcher/blob/master/app.py#L91
Looks like you don't need to login to get nukes, not sure about everything else.
