### ISSUE TITLE
is this for me?

### ISSUE THREAD

**Issue by yandexman** [unknown321/mgsv_emulator#5]
Hello mate

Can i hack some MB coins with server emulator?
All i want is some MB coins to finish online weapons faster.
I am using a cheat engine script reward editor and there is an option for MB coins and says needs server auth. could that be done?

**Comment by unknown321** [comment]
Depends on what do you want. 

Server emulator is supposed to be a replacement for konami's server - with new user profiles, stats, etc (including mb coins). If you want to get all weapons and don't mind being separated from the rest of the players - this is for you. If you want to get more mbcoins and play with others who don't use emulator, you are out of luck.

Btw, may I take a look at CE script of yours (with link to the post on CE forums if possible)? I feel like it is outdated.

**Comment by yandexman** [comment]
Here you go.
[MGSVTPP (7).zip](https://github.com/unknown321/mgsv_emulator/files/1395526/MGSVTPP.7.zip)

It was a collection of CE scripts in a rar archive i found on youtube. I read in comments CE forums had some kind of issue? and someone made an archive with all mgsv scripts.

Ye i wanted mb coins and play officials.These research times irritates me.

Cheers

**Comment by unknown321** [comment]
Hacked MB coins and official server is an impossible combination. Amount of mb coins is checked on server, unlike everything else. You can get literally any reward locally and it will be pushed to the server, but mb coins are different. When you start the game, you get the amount of coins you own from the server and any manipulations with them are performed on server. I guess the creator of that table tried to push changed amount of coins to konami server, got an error/was rejected and decided that you need to be authorized or something like that.

You have two options:

* forget about official server and use emulated one. Pros: no development times, custom fob events, everything is unlocked. Cons: no players to compete against.

* buy more coins

First option is fine as long as you don't care about leaderboards and stuff like that. The only downside is that it is under development and unusuable atm, so you'll have to wait for unknown amount of time for me to finish.
