### ISSUE TITLE
struct.error: argument out of range

### ISSUE THREAD

**Issue by alissonmuller** [unknown321/mgsv_emulator#7]
When I try to run the sample app (mgsv_nuke_watcher), I get the following error:
```
Traceback (most recent call last):
  File "app.py", line 126, in <module>
    gather_data()
  File "app.py", line 83, in gather_data
    steam_client.login()
  File "D:\git\mgsv_nuke_watcher\mgsv_emulator\emulator\client.py", line 100, in login
    response = self.send_command(i)
  File "D:\git\mgsv_nuke_watcher\mgsv_emulator\emulator\client.py", line 62, in send_command
    encrypted_request = self.__encoder__.encode(comm)
  File "D:\git\mgsv_nuke_watcher\mgsv_emulator\emulator\encoder.py", line 103, in encode
    text = base64.encodestring(self.__encipher__(self.__static_blowfish__, bytearray(text)))
  File "D:\git\mgsv_nuke_watcher\mgsv_emulator\emulator\encoder.py", line 52, in __encipher__
    x_text = struct.pack(ENCODE_PACK,x)
struct.error: argument out of range
```
blow.blowfish_encipher(x, y) is returning negative values on x and y, and it seems that ENCODE_PACK doesn't accept negative values (on my case, sys.maxsize > 2**32 evaluates to True)
```
ENCODE_PACK = '>l'
if sys.maxsize > 2**32:
	ENCODE_PACK = '>L'
```
What could be going on?
By the way, I'm on Windows 7 64 bit, using Python 3.6.2 64 bit.

**Comment by unknown321** [comment]
Ehh, I haven't tried running it on windows - everything is running in docker or linux machine. Both of them are x64, python 3.4

Try to enforce `ENCODE_PACK` to be `'>l'` - just remove if condition. I remember having troubles with it as well, thought it was fixed.

**Comment by alissonmuller** [comment]
Enforcing `ENCODE_PACK` to be `'>l'` worked on Windows, but not on Linux.
To make it work on both systems, I had to put an extra condition on the `if` statement:
```
ENCODE_PACK = '>l'
if platform.system() == 'Linux' and sys.maxsize > 2**32:
	ENCODE_PACK = '>L'
```
Also, I did the same thing on decoder.py (using `DECODE_PACK`, of course).
Thanks for the help! :-)

**Comment by unknown321** [comment]
Can you make a pull request for both files? Thanks.
